sonar.projectKey=Enzobu_GMAO_81882c00-d927-4c30-85f8-a0a5a8983d34
sonar.projectName=GMAO

sonar.sources=api/src,frontend/src
sonar.tests=api/tests

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/vendor/**,**/node_modules/**,**/var/**,**/dist/**,**/build/**,**/public/build/**,**/migrations/**,docs/**
sonar.coverage.exclusions=frontend/**/*,docs/**

sonar.php.coverage.reportPaths=api/var/coverage/clover.xml
