api_platform:
    title: GMAO Api
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_items_per_page: 12
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 36
    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
