INSERT INTO maintenance_type (name, description, is_deleted) VALUES
('Vidange', NULL, 0),
('Filtre à huile', NULL, 0),
('Filtre à air', NULL, 0),
('Filtre d’habitacle', NULL, 0),
('Filtre à carburant', NULL, 0),
('Bougies', NULL, 0),
('Bougies de préchauffage', NULL, 0),
('Plaquettes de frein', NULL, 0),
('Disques de frein', NULL, 0),
('Liquide de frein', NULL, 0),
('Liquide de refroidissement', NULL, 0),
('Courroie de distribution', NULL, 0),
('Courroie accessoire', NULL, 0),
('Embrayage', NULL, 0),
('Huile de boîte', NULL, 0),
('Suspension', NULL, 0),
('Batterie', NULL, 0),
('Pneus', NULL, 0),
('Kit chaîne', NULL, 0),
('Préparation contrôle technique', NULL, 0),
('Autre', NULL, 0);
